### ISSUE TITLE
Unable to build:prod

### ISSUE THREAD

**Issue by alecpblack** [cebor/ng2-start#43]
After cloning and npm install, I get this error when running npm run build:prod.

ERROR in Cannot read property 'getSourceFile' of undefined

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './../$$_gendir/src/app/app.module.ngfact
ory' in 'c:\Visual Studio 2015 Projects\ng2-start\src'
 @ ./src/main.ts 3:0-81

Installed versions: node 7.7.4, npm 4.1.2

What am I missing or miss understanding?

--alec

**Comment by cebor** [comment]
hi, i cannot reproduce this? mabe a problem with your os.

does the official angular-cli works for you?
